config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :bookmarks, only: [:create]
  end

  resources :movies, only: [:index, :show]
  resources :bookmarks, only: [:new]
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  # created by has_many method
  # def movies
  #   Movie.joins(:bookmarks).where("bookmarks.list_id = self.id")
  # end
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true
  has_many :bookmarks
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list
  before_action :find_bookmark, only: [:destroy]

  def new
    @bookmark = @list.bookmarks.build
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@list), notice: 'Bookmark was successfully destroyed.'
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def find_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all, prompt: "Select a movie" %>
  <%= f.input :list_id, collection: List.all, prompt: "Select a list" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class = "container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div id="container" class="container">
  <h1 class="text-white text-bold">Your place to organize what you want to see</h1>
  <div class="text-center"> <!-- Center align the content -->
    <%= link_to "Create list", new_list_path, class: "btn btn-primary btn-lg btn-create-list" %>
  </div>

  <div id="lists" class="row justify-content-center">
    <% @lists.each do |list| %>
      <div class="col-md-3">
        <ul>
          <li><%= link_to list.name, list_path(list), class: "text-white" %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1>My <%= @list.name %> Movies</h1>

<% @list.bookmarks.each do |bookmark| %>
  <p>
    <%= bookmark.movie.title %> - <%= bookmark.comment %>
  </p>
<% end %>